name: Daily Test

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    name: Daily Test on Node.js
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Node.js
      uses: actions/setup-node@v1

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test:irl
